# Generated by Django 5.2.6 on 2025-09-24 17:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oggetto',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='oggetti/'),
        ),
        migrations.AddField(
            model_name='oggetto',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scambio.location'),
        ),
        migrations.AddField(
            model_name='scatola',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scambio.location'),
        ),
        migrations.CreateModel(
            name='MerceScambiata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('oggetto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scambio.oggetto')),
                ('scatola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scambio.scatola')),
            ],
        ),
        migrations.CreateModel(
            name='Scambi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to='scambio.location')),
                ('da', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mittente', to='scambio.location')),
                ('merceScambiata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scambio.mercescambiata')),
            ],
        ),
    ]
