# Generated by Django 5.2.6 on 2025-09-24 18:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambio', '0002_oggetto_immagine_oggetto_location_scatola_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scambi',
            name='da',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mittente_scambio', to='scambio.location'),
        ),
        migrations.CreateModel(
            name='Noleggio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('a', models.CharField(max_length=200)),
                ('ritorno', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('da', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mittente_noleggio', to='scambio.location')),
            ],
        ),
    ]
