# Generated by Django 5.2.6 on 2025-09-24 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambio', '0003_alter_scambi_da_noleggio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scambi',
            name='a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario_scambio', to='scambio.location'),
        ),
    ]
