# Generated by Django 5.2.6 on 2025-09-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambio', '0004_alter_scambi_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='nome',
            field=models.CharField(default='Campeione 1', max_length=200),
        ),
    ]
