# Generated by Django 5.2.6 on 2025-09-24 21:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambio', '0005_location_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercescambiata',
            name='createdAt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
