# Generated by Django 5.2.6 on 2025-09-24 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scambio', '0006_mercescambiata_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercescambiata',
            name='createdAt',
        ),
    ]
