# Generated by Django 5.2.6 on 2025-09-25 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambio', '0007_remove_mercescambiata_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scambi',
            name='merceScambiata',
        ),
        migrations.AddField(
            model_name='mercescambiata',
            name='scambo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scambio.scambi'),
        ),
    ]
