# Generated by Django 5.2.6 on 2025-09-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scambio', '0008_remove_scambi_mercescambiata_mercescambiata_scambo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mercescambiata',
            old_name='scambo',
            new_name='scambio',
        ),
    ]
