# Generated by Django 5.2.6 on 2025-09-25 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambio', '0009_rename_scambo_mercescambiata_scambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oggetto',
            name='scatola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scambio.scatola'),
        ),
    ]
