# Generated by Django 5.2.6 on 2025-09-25 20:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambio', '0010_alter_oggetto_scatola'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatola',
            name='createdAt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
