# Generated by Django 5.2.6 on 2025-09-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambio', '0012_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='hash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
