# Generated by Django 5.2.6 on 2025-09-26 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scambio', '0013_password_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='hash',
            new_name='dioHash',
        ),
    ]
