# Generated by Django 5.2.6 on 2025-09-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambio', '0014_rename_hash_password_diohash'),
    ]

    operations = [
        migrations.AddField(
            model_name='oggetto',
            name='dimensione',
            field=models.CharField(choices=[('piccolo', 'piccolo'), ('piccolo', 'medio'), ('piccolo', 'grande')], default='piccolo', max_length=200),
        ),
    ]
